mode: erase

dataset: cifar100

transform: ['erase']
random_aug: False
global_aug: False

li_flag: True #!
load_li: False #!
train_copies: 1 
test_time_aug: False
test_copies: 10 
lr: 0.00001 #!#!
warmup_period: 5

crop_layer: [1, -1] #!
crop_layer_bias: [1, 3] #!

entropy_weights: [0.2]
#entropy_weights: [0.2] #For supervised
#entropy_weights: [0.03] #For contrastive? 
    
#Be careful of the order of min and max
entropy_max_thresholds: [3] #~
entropy_min_thresholds: [3.5] #~

entropy_increase_period: 40

scheduler_sleep_epoch: 0 #!
ConvFeature: True

max_black_ratio: 0.2

crop_only_for_tpu: True
zoom_min: 0.05
zoom_max: 0.3
zoom_step: 50
translation_min: -1
translation_max: 1
translation_step: 50
input_size: 32